// export const FIELD_KEYS = [
//   "amenities_title",
//   "c_latitude",
//   "c_longitude",
//   "career_sec2_flipbox_description",
//   "career_sec2_flipbox_title",
//   "career_sec3_infobox_description",
//   "career_sec3_infobox_description1",
//   "career_sec3_infobox_title",
//   "career_sec3_infobox_title1",
//   "career_sec5_accord_description",
//   "career_sec5_accord_no",
//   "career_sec5_accord_title",
//   "career_sec7_iconbox_title",
//   "career_testimonial_title",
//   "exterior_block_id",
//   "exterior_description",
//   "exterior_fwidth",
//   "exterior_iwidth",
//   "exterior_position",
//   "exterior_title",
//   "exterior_x_value",
//   "exterior_y_value",
//   "faq_description",
//   "faq_description_2",
//   "faq_no",
//   "faq_no_2",
//   "faq_title",
//   "faq_title_2",
//   "glance_big_hd",
//   "glance_para",
//   "ia_description",
//   "ia_title",
//   "ic_latitude",
//   "ic_longitude",
//   "ii_description",
//   "ii_title",
//   "incity_c_latitude",
//   "incity_c_longitude",
//   "incity_ic_latitude",
//   "incity_ic_longitude",
//   "incity_info_list_title",
//   "incity_location_km",
//   "incity_location_name",
//   "incity_map_embed",
//   "incity_no",
//   "incity_person_email",
//   "incity_person_name",
//   "incity_person_number",
//   "indicator_description",
//   "indicator_no",
//   "interior_description",
//   "interior_fwidth",
//   "interior_id",
//   "interior_iwidth",
//   "interior_position",
//   "interior_title",
//   "interior_x_value",
//   "interior_y_value",
//   "list_text",
//   "location_km",
//   "location_name",
//   "ma_latitude",
//   "ma_longitude",
//   "map_embed",
//   "matters_description",
//   "matters_title",
//   "media_name",
//   "media_person_mail",
//   "media_person_mobile",
//   "media_person_name",
//   "no",
//   "person_email",
//   "person_name",
//   "person_number",
//   "pr_description",
//   "pr_heading",
//   "slider_description",
//   "state_name_region",
//   "state_url",
//   "amen_source_link",
//   "amenities_list",
//   "amenities_para",
//   "blog_publish_date",
//   "career_sec1_heading",
//   "career_sec1_paragraph",
//   "career_sec2_flipbox",
//   "career_sec2_heading",
//   "career_sec2_sub_paragraph",
//   "career_sec3_heading",
//   "career_sec3_infobox",
//   "career_sec3_infobox_copy",
//   "career_sec3_sub_paragraph",
//   "career_sec4_description",
//   "career_sec4_heading",
//   "career_sec5_accordion",
//   "career_sec6_heading",
//   "career_sec6_url",
//   "career_sec7_heading",
//   "career_sec7_iconbox",
//   "career_sec8_heading",
//   "career_spotlight_title",
//   "category_id",
//   "closer_paragraph",
//   "closer_titile",
//   "connectivity",
//   "construction_status",
//   "coordinates_no",
//   "coordinates_url",
//   "customer_name",
//   "date",
//   "delhi_micro_blog_h1_tag",
//   "designation",
//   "development_potential",
//   "exterior_block",
//   "extra_paragraph",
//   "faq_list",
//   "faq_list_2",
//   "glance_details",
//   "goa_micro_blog_h1_tag",
//   "gujarat_micro_blog_h1_tag",
//   "h1_tag",
//   "haryana_micro_blog_h1_tag",
//   "hyderabad_micro_blog_h1_tag",
//   "igbc_logo",
//   "igbc_status",
//   "incentivised_list",
//   "incentivised_title",
//   "incity_3d_h1",
//   "incity_3d_h2",
//   "incity_3d_url",
//   "incity_amenities",
//   "incity_city_name",
//   "incity_connectivity",
//   "incity_construction_status",
//   "incity_coordinates_no",
//   "incity_coordinates_url",
//   "incity_development_potential",
//   "incity_h1_tag",
//   "incity_hd_para",
//   "incity_hd_title",
//   "incity_igbc_logo",
//   "incity_igbc_status",
//   "incity_industrial_clusters_nearby",
//   "incity_info_list_box",
//   "incity_infrastructure",
//   "incity_land_area",
//   "incity_land_usage",
//   "incity_leasing_details_rep",
//   "incity_main_access",
//   "incity_masterplan_h1",
//   "incity_masterplan_h2",
//   "incity_name",
//   "incity_para1",
//   "incity_park_address",
//   "incity_park_availability",
//   "incity_park_city",
//   "incity_park_status",
//   "incity_parks_schema",
//   "incity_pin_color",
//   "incity_read_more_para",
//   "incity_svg_x",
//   "incity_svg_y",
//   "incity_text_position_",
//   "incity_zone_name",
//   "indicator_data",
//   "industrial_clusters_nearby",
//   "industry",
//   "interior_block",
//   "karnataka_micro_blog_h1_tag",
//   "key_paragraph",
//   "key_title",
//   "land_area",
//   "land_usage",
//   "leasing_details",
//   "m_news_description",
//   "m_news_link",
//   "m_news_platform",
//   "m_news_publish_date",
//   "maha_micro_blog_h1_tag",
//   "main_access",
//   "manufac_source_link",
//   "map_button_text",
//   "map_button_url",
//   "matter_icon_box",
//   "matters_hd1",
//   "matters_hd2",
//   "media_contact_details",
//   "new_site_plan",
//   "overview_paragraph",
//   "overview_title",
//   "paragraph",
//   "paragraph1",
//   "paragraph_incen",
//   "paragraph_parks",
//   "park_hd_para",
//   "park_name",
//   "park_para1",
//   "park_status",
//   "parks_schema",
//   "photo",
//   "pin_color",
//   "pr_publish_date",
//   "pr_sub_heading",
//   "prblm_paragraph",
//   "prblm_title",
//   "product_manufacture_paragraph",
//   "product_manufacture_readmore_paragraph",
//   "product_manufacture_title",
//   "publish_date",
//   "publish_month",
//   "publish_year",
//   "read_more_para_park",
//   "region_slider",
//   "section_title",
//   "section_title1",
//   "section_title_incen",
//   "section_title_indic",
//   "section_title_manuf",
//   "section_title_parks",
//   "section_title_region",
//   "sector_paragraph",
//   "sector_title",
//   "select_parks",
//   "short_date",
//   "site_plan",
//   "slider_data",
//   "small_description",
//   "solution_paragraph",
//   "solution_title",
//   "source_link",
//   "state_name",
//   "state_park_title_1",
//   "state_park_title_2",
//   "sub_paragraph",
//   "sub_title",
//   "svg_x",
//   "svg_y",
//   "tamil_nadu_micro_blog_h1_tag",
//   "telangana_micro_blog_h1_tag",
//   "telangana_micro_blog_publish_date",
//   "telangana_micro_short_date",
//   "text_position",
//   "zone_name",
// ];
export const FIELD_KEYS = {
  headings: [
    "amenities_title",
    "career_sec2_flipbox_title",
    "career_sec3_infobox_title",
    "career_sec3_infobox_title1",
    "career_sec5_accord_title",
    "career_sec7_iconbox_title",
    "career_testimonial_title",
    "exterior_title",
    "faq_title",
    "faq_title_2",
    "glance_big_hd",
    "ia_title",
    "ii_title",
    "incity_info_list_title",
    "interior_title",
    "location_name",
    "matters_title",
    "media_name",
    "person_name",
    "pr_heading",
    "state_name_region",
    "career_sec1_heading",
    "career_sec2_heading",
    "career_sec3_heading",
    "career_sec4_heading",
    "career_sec6_heading",
    "career_sec7_heading",
    "career_sec8_heading",
    "career_spotlight_title",
    "category_id",
    "closer_titile",
    "delhi_micro_blog_h1_tag",
    "designation",
    "goa_micro_blog_h1_tag",
    "gujarat_micro_blog_h1_tag",
    "h1_tag",
    "haryana_micro_blog_h1_tag",
    "hyderabad_micro_blog_h1_tag",
    "incentivised_title",
    "incity_3d_h1",
    "incity_3d_h2",
    "incity_city_name",
    "incity_h1_tag",
    "incity_hd_title",
    "incity_masterplan_h1",
    "incity_masterplan_h2",
    "incity_name",
    "incity_park_city",
    "industry",
    "karnataka_micro_blog_h1_tag",
    "key_title",
    "land_usage",
    "maha_micro_blog_h1_tag",
    "matters_hd1",
    "matters_hd2",
    "overview_title",
    "park_name",
    "park_status",
    "section_title",
    "section_title1",
    "section_title_incen",
    "section_title_indic",
    "section_title_manuf",
    "section_title_parks",
    "section_title_region",
    "sector_title",
    "solution_title",
    "state_name",
    "state_park_title_1",
    "state_park_title_2",
    "sub_title",
    "tamil_nadu_micro_blog_h1_tag",
    "telangana_micro_blog_h1_tag",
    "zone_name",
  ],

  slugs: [
    "state_url",
    "amen_source_link",
    "career_sec6_url",
    "coordinates_url",
    "manufac_source_link",
    "map_button_url",
    "m_news_link",
    "source_link",
    "coordinates_url",
    "incity_coordinates_url",
    "incity_3d_url",
  ],

  descriptions: [
    "c_latitude",
    "c_longitude",
    "career_sec2_flipbox_description",
    "career_sec3_infobox_description",
    "career_sec3_infobox_description1",
    "career_sec5_accord_description",
    "career_sec5_accord_no",
    "exterior_block_id",
    "exterior_description",
    "exterior_fwidth",
    "exterior_iwidth",
    "faq_description",
    "faq_description_2",
    "faq_no",
    "faq_no_2",
    "glance_para",
    "ia_description",
    "ic_latitude",
    "ic_longitude",
    "ii_description",
    "incity_c_latitude",
    "incity_c_longitude",
    "incity_ic_latitude",
    "incity_ic_longitude",
    "incity_location_km",
    "incity_location_name",
    "incity_map_embed",
    "incity_no",
    "incity_person_email",
    "incity_person_number",
    "indicator_description",
    "indicator_no",
    "interior_description",
    "interior_fwidth",
    "interior_id",
    "interior_iwidth",
    "list_text",
    "location_km",
    "ma_latitude",
    "ma_longitude",
    "map_embed",
    "matters_description",
    "media_person_mail",
    "media_person_mobile",
    "no",
    "person_email",
    "person_number",
    "pr_description",
    "slider_description",
    "amenities_list",
    "amenities_para",
    "career_sec1_paragraph",
    "career_sec2_flipbox",
    "career_sec2_sub_paragraph",
    "career_sec3_infobox",
    "career_sec3_infobox_copy",
    "career_sec3_sub_paragraph",
    "career_sec4_description",
    "career_sec5_accordion",
    "career_sec7_iconbox",
    "coordinates_no",
    "customer_name",
    "development_potential",
    "exterior_block",
    "extra_paragraph",
    "faq_list",
    "faq_list_2",
    "glance_details",
    "igbc_logo",
    "igbc_status",
    "incentivised_list",
    "incity_amenities",
    "incity_connectivity",
    "incity_construction_status",
    "incity_coordinates_no",
    "incity_development_potential",
    "incity_hd_para",
    "incity_industrial_clusters_nearby",
    "incity_info_list_box",
    "incity_infrastructure",
    "incity_land_area",
    "incity_land_usage",
    "incity_leasing_details_rep",
    "incity_main_access",
    "incity_para1",
    "incity_park_address",
    "incity_park_availability",
    "incity_parks_schema",
    "incity_pin_color",
    "incity_read_more_para",
    "indicator_data",
    "industrial_clusters_nearby",
    "interior_block",
    "key_paragraph",
    "land_area",
    "leasing_details",
    "m_news_description",
    "m_news_platform",
    "main_access",
    "map_button_text",
    "matter_icon_box",
    "media_contact_details",
    "new_site_plan",
    "overview_paragraph",
    "paragraph",
    "paragraph1",
    "paragraph_incen",
    "paragraph_parks",
    "park_hd_para",
    "park_para1",
    "parks_schema",
    "photo",
    "pin_color",
    "pr_sub_heading",
    "prblm_paragraph",
    "prblm_title",
    "product_manufacture_paragraph",
    "product_manufacture_readmore_paragraph",
    "product_manufacture_title",
    "publish_month",
    "publish_year",
    "read_more_para_park",
    "region_slider",
    "sector_paragraph",
    "select_parks",
    "site_plan",
    "slider_data",
    "small_description",
    "solution_paragraph",
    "sub_paragraph",
  ],
};

export const API_ENDPOINTS = [
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/client_stories",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/incity_parks",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/parks",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/posts",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/media_news",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/press_release",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/events",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/states",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/career_page",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/customers_speak",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/goa_micro_blog",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/delhi_micro_blog",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/gujarat_micro_blog",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/tamil_nadu_micro_blo",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/telangana_micro_blog",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/karnataka_micro_blog",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/haryana_micro_blog",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/maharasht_micro_blog",
  "https://phpstack-725513-2688800.cloudwaysapps.com/cms/wp-json/wp/v2/hyderabad_micro_blog",
];
